spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/sweater
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

  #  для передачи csrf от Spring Security
  freemarker:
      expose-request-attributes: true

  # Настройка ограничений на загрузку файлов
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  # Настройки Spring Mail Sender
  mail:
    host: smtp.gmail.com
    protocol:  smtps
    port: 465
    username: [ваша почта на gmail]
    password: [пароль от приложения]

mail:
  debug: true


# Папка для хранения картинок
upload:
  path: 'C:\Git\sweater\upload\'
