spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/sweater
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  #  для передачи csrf от Spring Security
  mustache:
    servlet:
      expose-request-attributes: true


