spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/sweater
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  #  для передачи csrf от Spring Security
  freemarker:
      expose-request-attributes: true

  # Настройка ограничений на загрузку файлов
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

upload:
  path: 'd:\git\letsCode\2022.09.19 - sweater\upload\'